<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [

	<!ELEMENT agenda (contacto)>
	<!ELEMENT contacto (nombre, apellido, apellidob, telefonofijo*, telefonomovil+)>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT apellido (#PCDATA)>
	<!ELEMENT apellidob (#PCDATA)>
	<!ELEMENT telefonofijo (#PCDATA)>
	<!ELEMENT telefonomovil (#PCDATA)>
]>

<agenda>
	<contacto>
		<nombre> felipe </nombre>
		<apellido>Castillo</apellido>
		<apellidob>Rodriguez</apellidob>
		<telefonofijo>923262626</telefonofijo>
		<telefonomovil>657575757</telefonomovil>
	</contacto>
</agenda>